<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 3/21/15
 * Time: 11:48
 */

class League extends DBAccess {
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new League();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct('leagues'); // TODO: Change the autogenerated stub
    }

}