<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 3/30/15
 * Time: 17:15
 */

class Match_Rule_Status extends DBAccess {
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Match_Rule_Status();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct('match_rule_status'); // TODO: Change the autogenerated stub
    }
}