<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 4/2/15
 * Time: 21:29
 */

class Match_Odd_Data extends DBAccess{
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Match_Odd_Data();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct('match_odd_data'); // TODO: Change the autogenerated stub
    }
}