<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 3/25/15
 * Time: 13:41
 */

class Odd extends DBAccess {
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Odd();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct('odds'); // TODO: Change the autogenerated stub
    }
}