<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 3/25/15
 * Time: 13:41
 */

class Odd extends DBAccess {
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Odd();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct('odds'); // TODO: Change the autogenerated stub
    }
    public function getOddbyType($type,$match_id) {
        $sql="select * from odds where type=? and match_id=? order by id desc";
        $result=DBConnection::read()->select($sql,array($type,$match_id));
        return $result;
    }
    public function getMatchExistingOdd() {
        $sql="select distinct match_id from odds";
        $result=DBConnection::read()->select($sql);
        $data=array();
        foreach ($result as $item) {
            $data[]=$item->match_id;
        }

        return $data;
    }
}