<?php
/**
 * Created by PhpStorm.
 * User: michael
 * Date: 3/30/15
 * Time: 11:45
 */

class Rules extends DBAccess {
    private static $instance;

    public static function getInstance()
    {
        if(self::$instance==null) {
            self::$instance=new Rules();
        }
        return self::$instance;
    }

    public function __construct()
    {
        parent::__construct('rules'); // TODO: Change the autogenerated stub
    }
    public function getRuleCount() {
        $sql="select data_type,count(*) as cnt from rules group by data_type";
        $result=DBConnection::read()->select($sql);

        $cnt=array();
        if(count($result)>0){
            foreach ($result as $item) {
                $cnt[$item->data_type]=$item->cnt;
            }
        }

        return $cnt;
    }
}